version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: triplytrip
    volumes:
      - .:/var/www/triplytrip
    ports:
      - "8000:8000"
    command: npm start

